# SELECT FIRST_HALF.FLAVOR FROM FIRST_HALF, ICECREAM_INFO 
# WHERE FIRST_HALF.TOTAL_ORDER > 3000 AND ICECREAM_INFO.INGREDIENT_TYPE = "fruit_based"
# AND FIRST_HALF.FLAVOR = ICECREAM_INFO.FLAVOR
# ORDER BY FIRST_HALF.TOTAL_ORDER DESC;

SELECT F.FLAVOR
FROM FIRST_HALF F, ICECREAM_INFO I
WHERE F.FLAVOR = I.FLAVOR AND F.TOTAL_ORDER > 3000 AND I.INGREDIENT_TYPE = 'fruit_based'
ORDER BY F.TOTAL_ORDER DESC;